version: '3.1'
services:

  front:
    build: ./Hack_2021_second-tage
    ports:
      - "3000:3000"

  app:
    build: ./
    ports:
      - "7777:7777"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
    - ./sql-init/1-startSql.sql:/docker-entrypoint-initdb.d/1-s.sql
    - ./csv-init/mcc.csv:/mcc.csv
    - ./csv-init/our_mcc.csv:/our_mcc.csv
    - ./csv-init/tr.csv:/tr.csv
    - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypointA.sh

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
